controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    dsr_controller2:
      type: dsr_controller2/RobotController

    dsr_joint_trajectory:
      type: dsr_joint_trajectory/RobotController

    dsr_joint_publisher:
      type: joint_state_controller/JointStateController

dsr_controller2:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    # command_interfaces:
    #   - position
    #   - velocity

    # state_interfaces:
    #   - position
    #   - velocity

dsr_joint_trajectory:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity
